#!/bin/bash

# Change directory to Downloads
cd ~/gh

# Check if the script exists
script_name="green"
if [ -f "$script_name" ]; then
    # Run the script
    ./"$script_name"
else
    echo "Error: Script '$script_name' not found in the Downloads directory."
fi

gh="cota"
if [ -f "$gh" ]; then
	./"$gh"
else
	echo "script '$gh' not found"
fi
